language: python
python:
- '3.6'
branches:
  only:
  - sources
env:
  global:
  - secure: Mp99FntT3ECutjODxYTshOHG/2nn9IMfpJtvzrJuo+j2Q2+9d74F2zdyA4RWeCp7XXO1v/uPdjirksPJi+oNUvwfiwntonJEWGICrWaMh8uBQQGBc0INzn5miOwGayTcsHyDwjInxylzs1lU2RhXd51GMIDqzFG70C90b6V89vQ=
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda config --set always_yes yes --set changeps1 no
- conda env create -q -f environment.yml -n test-environment
- source activate test-environment
install: true
script:
- make publish-to-github-force
